$(function(){var timer=$('#timer'),timerTop=$('.top img',timer),timerBottom=$('.top2 img',timer);var thumbs=$('#thumbscarousel');var slidedetail=$('.slide-detail');$('.slide ul').carouFredSel({prev:'#prevslide',next:'#nextslide',pagination:".button",items:1,auto:{pauseOnEvent:'resume',button:'#play',progress:{bar:'#timer',updater:function(percentage){if(percentage<50){var deg=180-(percentage*180/50);timerTop.css('transform','rotate( -'+deg+'deg )');timerBottom.css('transform','rotate( 0deg )');}else{var deg=((percentage-50)*180/50);timerTop.css('transform','rotate( 0deg )');timerBottom.css('transform','rotate( '+deg+'deg )');}}}},onCreate:function(){slidedetail.animate({left:'0'})},scroll:{duration:1500,fx:"crossfade",onBefore:function(){timer.hide();slidedetail.animate({left:'-220px'})},onAfter:function(){timer.show();timerTop.css('transform','rotate( 182deg )');timerBottom.css('transform','rotate( 0deg )');slidedetail.animate({left:'0'})}}});thumbs.carouFredSel({circular:false,auto:false,width:150,height:75,scroll:{duration:200},items:{visible:1,width:150,height:75}});$('.button a').hover(function(){var current=$('.slider').triggerHandler('currentPosition');thumbs.trigger('slideTo',[current,0,true,{fx:'none'}]);$('#thumbs').stop().fadeTo(300,1);},function(){$('#thumbs').stop().fadeTo(300,0);});$('.button a').mouseenter(function(){var index=$('.button a').index($(this));thumbs.trigger('queue',[[]]);thumbs.trigger('slideTo',[index,{queue:true}]);});});$(document).ready(function(){if($.browser.ipad||$.browser.iphone||$.browser.android){$('.NowruzTourBanner, .right-nav-menu').css({'position':'absolute',});}
$('.search-input').bind('focus',function(){$('.toolbar-right').addClass('search-active');});$('.search-input').bind('blur',function(){$('.toolbar-right').removeClass('search-active');});$('.toolbar-login-link a').click(function(){$('.toolbar-register-box').slideUp('fast',function(){$('.toolbar-login-box').slideToggle();})
return false;})
$('.toolbar-register-link a').click(function(){$('.toolbar-login-box').slideUp('fast',function(){$('.toolbar-register-box').slideToggle();})
return false;})
$('.toolbar-tour-link a').mouseenter(function(){$('.list-box').slideDown('fast')})
$('.toolbar').mouseleave(function(){$('.list-box').slideUp('fast')})
$('.list-box .myTree li').mouseover(function(){$('.list-box .myTree li').css({'z-index':'-9999'});$(this).css({'z-index':'999'});})
$('.right-nav-item').mouseover(function(){$(this).stop().animate({right:'0'},{queue:false,duration:150});})
$('.right-nav-item').mouseout(function(){$(this).stop().animate({right:'-119px'},{queue:false,duration:150});})
$('.special-ads ul li').mouseover(function(){$(this).find('span').stop().animate({height:'60px'},{queue:false,duration:200});})
$('.special-ads ul li').mouseout(function(){$(this).find('span').stop().animate({height:'20px'},{queue:false,duration:200});})});$(function(){$('#tabs').carouFredSel({circular:false,items:1,width:'100%',auto:false,pagination:{container:'#pager',anchorBuilder:function(nr){return'<a href="#">'+$(this).find('h2').text()+'</a>';}},prev:'.prev-tab',next:'.next-tab',});});$(function(){$('#tabs2').carouFredSel({circular:false,items:1,width:'100%',auto:false,pagination:{container:'#pager2',anchorBuilder:function(nr){return'<a href="#">'+$(this).find('h2').text()+'</a>';}},prev:'.prev-tab2',next:'.next-tab2',});});$(document).ready(function(){$('.lImage').cycle({fx:'fade'});$('.topShutIt').click(function(){$(this).parent().css('display','none');$(this).css('display','none');});});